# -*- coding: utf-8 -*-
"""Books, translations, the trail network and events.

Split from content.py only for readability; it is the same dataset.
"""

# ---------------------------------------------------------------------------
# Books.  (id, title, author, imprint, year, genre, original_language)
# Pages, price and ISBN are generated from the fixed seed, so they are stable
# across builds without anyone having to invent seventy of them.
# ---------------------------------------------------------------------------
BOOKS = [
    ("cold-harbour",         "Cold Harbour",           "rhona-blackwood",  "northwind",       1948, "literary-fiction",    "en"),
    ("the-lamp-room",     "The Lamp Room",       "rhona-blackwood",  "northwind",       1955, "literary-fiction",    "en"),
    ("afon-hir",             "Afon Hir",               "iolo-vaughan",     "greenslate",      1951, "poetry",              "cy"),
    ("the-long-river",       "The Long River",         "iolo-vaughan",     "greenslate",      1963, "poetry",              "cy"),
    ("north-of-the-tweed",   "North of the Tweed",     "gerard-tyne",      "harbourmaster",   1947, "maritime-history",    "en"),
    ("herring-and-hemp",     "Herring and Hemp",       "gerard-tyne",      "harbourmaster",   1959, "maritime-history",    "en"),
    ("the-quarry-glass",     "The Quarry Glass",       "maud-ellery",      "thornfield",      1961, "literary-fiction",    "en"),
    ("evensong-for-a-thief", "Evensong for a Thief",   "maud-ellery",      "thornfield",      1968, "crime-fiction",       "en"),
    ("the-shieling",         "The Shieling",           "callum-strachan",  "cairn",           1964, "historical-fiction",  "gd"),
    ("nine-winters",         "Nine Winters",           "callum-strachan",  "cairn",           1972, "historical-fiction",  "gd"),
    ("hedgerow-alphabet",    "A Hedgerow Alphabet",    "perrin-oakes",     "thornfield",      1966, "nature-writing",      "en"),
    ("the-marches",          "The Marches",            "perrin-oakes",     "thornfield",      1974, "travel-writing",      "en"),
    ("llyfr-y-mynydd",       "Llyfr y Mynydd",         "nesta-hywel",      "greenslate",      1969, "nature-writing",      "cy"),
    ("the-mountain-book",    "The Mountain Book",      "nesta-hywel",      "greenslate",      1977, "nature-writing",      "cy"),
    ("dockhead",             "Dockhead",               "dermot-lisle",     "lodestone-group", 1971, "industrial-history",  "en"),
    ("the-pilot-boat",       "The Pilot Boat",         "dermot-lisle",     "harbourmaster",   1980, "crime-fiction",       "en"),
    ("minster-yard",         "Minster Yard",           "agnes-varden",     "thornfield",      1975, "cosy-crime",          "en"),
    ("the-chapter-house",    "The Chapter House",      "agnes-varden",     "thornfield",      1982, "cosy-crime",          "en"),
    ("a-cold-coming",        "A Cold Coming",          "agnes-varden",     "pica",            1991, "police-procedural",   "en"),
    ("sgeulachdan-mara",     "Sgeulachdan Mara",       "torin-mackay",     "cairn",           1978, "folk-fantasy",        "gd"),
    ("the-selkie-ledger",    "The Selkie Ledger",      "torin-mackay",     "cairn",           1986, "folk-fantasy",        "gd"),
    ("coal-and-chapel",      "Coal and Chapel",        "bryn-caradoc",     "greenslate",      1983, "industrial-history",  "cy"),
    ("the-tramroad",         "The Tramroad",           "bryn-caradoc",     "greenslate",      1992, "local-history",       "cy"),
    ("the-orrery",           "The Orrery",             "selina-frayne",    "pica",            1984, "historical-fiction",  "en"),
    ("pump-room-winter",     "Pump Room Winter",       "selina-frayne",    "pica",            1993, "historical-fiction",  "en"),
    ("the-cotton-line",      "The Cotton Line",        "hal-morrow",       "lodestone-group", 1987, "industrial-history",  "en"),
    ("smokestack",           "Smokestack",             "hal-morrow",       "lodestone-group", 1996, "literary-fiction",    "en"),
    ("the-glasshouse",       "The Glasshouse",         "ines-calloway",    "thornfield",      1989, "literary-fiction",    "en"),
    ("river-terminus",       "River Terminus",         "ines-calloway",    "thornfield",      1999, "literary-fiction",    "en"),
    ("the-quiet-service",    "The Quiet Service",      "ines-calloway",    "pica",            2007, "crime-fiction",       "en"),
    ("fell-and-force",       "Fell and Force",         "fenella-drew",     "northwind",       1990, "nature-writing",      "en"),
    ("the-limestone-year",   "The Limestone Year",     "fenella-drew",     "northwind",       2000, "geology",             "en"),
    ("cerrig-a-chysgod",     "Cerrig a Chysgod",       "owain-preece",     "cwm-press",       1994, "poetry",              "cy"),
    ("stones-and-shadow",    "Stones and Shadow",      "owain-preece",     "cwm-press",       2003, "poetry",              "cy"),
    ("the-clyde-tapes",      "The Clyde Tapes",        "kirsty-lammond",   "northwind",       1995, "tartan-noir",         "en"),
    ("dead-reckoning",       "Dead Reckoning",         "kirsty-lammond",   "northwind",       2002, "tartan-noir",         "en"),
    ("the-govan-inheritance","The Govan Inheritance",  "kirsty-lammond",   "bell-rock",       2011, "tartan-noir",         "en"),
    ("the-third-map",        "The Third Map",          "marek-oyelaran",   "thornfield",      1998, "speculative-fiction", "en"),
    ("orbital-decay",        "Orbital Decay",          "marek-oyelaran",   "pica",            2005, "hard-sf",             "en"),
    ("the-long-station",     "The Long Station",       "marek-oyelaran",   "pica",            2013, "space-opera",         "en"),
    ("the-fen-tiger",        "The Fen Tiger",          "delia-stannard",   "saltmarsh",       2001, "historical-fiction",  "en"),
    ("drainage",             "Drainage",               "delia-stannard",   "saltmarsh",       2009, "nature-writing",      "en"),
    ("the-book-town",        "The Book Town",          "rab-fingal",       "bell-rock",       2004, "cosy-crime",          "en"),
    ("a-margin-of-error",    "A Margin of Error",      "rab-fingal",       "bell-rock",       2012, "cosy-crime",          "en"),
    ("whalebone-street",     "Whalebone Street",       "juno-verrall",     "harbourmaster",   2006, "historical-fiction",  "en"),
    ("the-jet-workers",      "The Jet Workers",        "juno-verrall",     "harbourmaster",   2014, "local-history",       "en"),
    ("y-mor-tywyll",         "Y Mor Tywyll",           "elin-morgan",      "cwm-press",       2008, "folk-fantasy",        "cy"),
    ("the-dark-sea",         "The Dark Sea",           "elin-morgan",      "cwm-press",       2016, "folk-fantasy",        "cy"),
    ("links-and-lies",       "Links and Lies",         "sandy-cleghorn",   "bell-rock",       2010, "police-procedural",   "en"),
    ("west-sands",       "West Sands",         "sandy-cleghorn",   "bell-rock",       2018, "police-procedural",   "en"),
    ("the-broad-and-the-cut","The Broad and the Cut",  "priya-nandakumar", "saltmarsh",       2011, "nature-writing",      "en"),
    ("saltmarsh-year",       "Saltmarsh Year",         "priya-nandakumar", "saltmarsh",       2019, "ornithology",         "en"),
    ("the-tenement-key",     "The Tenement Key",       "tam-brodie",       "northwind",       2013, "tartan-noir",         "en"),
    ("closes-and-wynds",     "Closes and Wynds",       "tam-brodie",       "northwind",       2021, "tartan-noir",         "en"),
    ("gwreiddiau",           "Gwreiddiau",             "cerys-lloyd",      "drovers-road",    2015, "poetry",              "cy"),
    ("rootstock",                "Rootstock",                  "cerys-lloyd",      "drovers-road",    2022, "poetry",              "cy"),
    ("the-crossing-season",  "The Crossing Season",    "noor-haddad",      "thornfield",      2016, "translated-fiction",  "ar"),
    ("a-second-country",     "A Second Country",       "noor-haddad",      "thornfield",      2023, "literary-fiction",    "ar"),
    ("the-tarn",             "The Tarn",               "bram-tillotson",   "wrenline",        2017, "mountaineering",      "en"),
    ("scree",                "Scree",                  "bram-tillotson",   "wrenline",        2024, "mountaineering",      "en"),
    ("the-tin-coast",        "The Tin Coast",          "orla-finnerty",    "tide-and-tiller", 2018, "folk-fantasy",        "en"),
    ("wrecking",             "Wrecking",               "orla-finnerty",    "tide-and-tiller", 2023, "maritime-history",    "en"),
    ("the-flood-meadow",     "The Flood Meadow",       "magnus-thole",     "wrenline",        2019, "climate-fiction",     "en"),
    ("high-water",           "High Water",             "magnus-thole",     "wrenline",        2025, "climate-fiction",     "en"),
    ("the-canal-and-the-mill","The Canal and the Mill","yara-tesfaye",     "lodestone-group", 2020, "industrial-history",  "en"),
    ("machine-time",         "Machine Time",           "yara-tesfaye",     "lodestone-group", 2024, "climate-fiction",     "en"),
    ("the-leat",             "The Leat",               "dilys-tremain",    "tide-and-tiller", 2021, "folk-fantasy",        "en"),
    ("granite-and-rain",     "Granite and Rain",       "dilys-tremain",    "tide-and-tiller", 2025, "nature-writing",      "en"),
]

# Series membership: a few books belong to a numbered series.  Gives ORDER BY
# and window-flavoured subqueries something to bite on.
SERIES = [
    ("mackenzie-files", "The Mackenzie Files", ["the-clyde-tapes", "dead-reckoning", "the-govan-inheritance"]),
    ("minster-mysteries", "The Minster Mysteries", ["minster-yard", "the-chapter-house", "a-cold-coming"]),
    ("wigtown-cases", "The Wigtown Cases", ["the-book-town", "a-margin-of-error"]),
    ("tide-trilogy", "The Tide Trilogy", ["the-tin-coast", "wrecking", "the-leat"]),
]

# Translations.  (id, title, of_book, language, direction, translator, year, imprint)
# The RTL rows are what the LANGDIR / hasLANGDIR lessons run on.
TRANSLATIONS = [
    ("the-dark-sea-ar",      "البحر المظلم",
     "the-dark-sea",      "ar", "rtl", "noor-haddad",  2019, "thornfield"),
    ("the-selkie-ledger-ar", "سجل السيلكي",
     "the-selkie-ledger", "ar", "rtl", "noor-haddad",  2001, "cairn"),
    ("cold-harbour-he",      "מעגן קר",
     "cold-harbour",      "he", "rtl", None,           1972, "lodestone-group"),
    ("the-book-town-cy",     "Y Dref Lyfrau",
     "the-book-town",     "cy", "ltr", "cerys-lloyd",  2009, "cwm-press"),
    ("the-tarn-gd",          "An Lochan",
     "the-tarn",          "gd", "ltr", "torin-mackay", 2020, "cairn"),
    ("the-long-station-cy",  "Yr Orsaf Hir",
     "the-long-station",  "cy", "ltr", "elin-morgan",  2017, "cwm-press"),
]

# ---------------------------------------------------------------------------
# The trail.  Mostly linear, with two branches, one loop, and a deliberately
# disconnected south-western spur -- so `bs:connectsTo+` returns a strictly
# smaller set than "every shop", and the learner can see exactly why.
# (from_shop, to_shop, waymarked)
# ---------------------------------------------------------------------------
TRAIL = [
    ("inkwell",        "marginalia",     True),
    ("marginalia",     "broken-spine",   True),
    ("inkwell",        "colophon",       True),
    ("broken-spine",   "colophon",       True),
    ("colophon",       "quire",          True),
    ("quire",          "verso",          True),
    ("verso",          "northern-light", True),
    ("northern-light", "sea-margin",     False),
    ("colophon",       "gutter-gilt",    True),
    ("gutter-gilt",    "borderprint",    True),
    ("borderprint",    "endpapers",      True),
    ("endpapers",      "bookwyrm",       True),
    ("bookwyrm",       "harbour-page",   True),
    ("endpapers",      "dales-folio",    True),
    ("dales-folio",    "errata",         True),
    ("errata",         "pressmark",      True),
    ("pressmark",      "bookbarrow",     True),
    ("bookbarrow",     "cotton-quarto",  False),
    ("cotton-quarto",  "signature",      True),
    ("signature",      "severn-leaf",    True),
    ("severn-leaf",    "dog-eared",      True),
    ("dog-eared",      "castle-steps",   True),
    ("castle-steps",   "clock-tower",    True),
    ("clock-tower",    "cliff-road",     True),
    ("cliff-road",     "taff-margin",    True),
    ("taff-margin",    "crescent",       True),
    ("crescent",       "candlemas",    True),
    ("candlemas",    "chapter-verse",  True),
    ("chapter-verse",  "broads-bindery", True),
    ("broads-bindery", "ex-libris",      True),
    ("ex-libris",      "turn-the-page",  True),
    ("turn-the-page",  "crescent",       False),   # closes a loop
    ("west-quay",      "penwith",        True),    # the isolated south-west spur
]

# ---------------------------------------------------------------------------
# Events.  Titles are composed from a kind and the featured author's work, so
# they read naturally without seventy hand-written strings.
# (shop, kind, iso_date, featured_author, attendance, ticket_price_gbp)
# ---------------------------------------------------------------------------
EVENTS = [
    ("inkwell",       "Reading",   "2025-03-08", "rab-fingal",       48,  0.00),
    ("inkwell",       "Signing",   "2025-06-14", "rab-fingal",       72,  0.00),
    ("inkwell",       "Panel",     "2025-09-27", "kirsty-lammond",  110,  8.50),
    ("marginalia",    "Reading",   "2025-04-19", "cerys-lloyd",      26,  5.00),
    ("marginalia",    "Workshop",  "2025-08-02", "owain-preece",     18, 22.00),
    ("colophon",      "Launch",    "2025-02-11", "tam-brodie",      185,  0.00),
    ("colophon",      "Lecture",   "2025-05-30", "ines-calloway",   140, 12.00),
    ("colophon",      "Book Club", "2025-10-16", "agnes-varden",     34,  4.00),
    ("broken-spine",  "Reading",   "2025-07-05", "tam-brodie",       55,  6.00),
    ("quire",         "Panel",     "2025-03-22", "yara-tesfaye",    130,  9.00),
    ("quire",         "Workshop",  "2025-11-08", "marek-oyelaran",   24, 30.00),
    ("verso",         "Launch",    "2025-05-17", "noor-haddad",      95,  0.00),
    ("verso",         "Reading",   "2025-09-13", "noor-haddad",      61,  7.00),
    ("gutter-gilt",   "Lecture",   "2025-04-26", "sandy-cleghorn",   88, 10.00),
    ("northern-light","Reading",   "2025-06-07", "torin-mackay",     42,  5.00),
    ("northern-light","Workshop",  "2025-08-23", "fenella-drew",     20, 25.00),
    ("sea-margin",    "Reading",   "2025-07-19", "torin-mackay",     31,  4.00),
    ("borderprint",   "Book Club", "2025-02-28", "juno-verrall",     22,  3.00),
    ("dales-folio",   "Lecture",   "2025-05-10", "fenella-drew",     76, 11.00),
    ("dales-folio",   "Reading",   "2025-10-04", "bram-tillotson",   58,  6.00),
    ("errata",        "Panel",     "2025-03-15", "marek-oyelaran",   45,  8.00),
    ("pressmark",     "Reading",   "2025-06-21", "magnus-thole",     67,  6.50),
    ("bookbarrow",    "Workshop",  "2025-09-06", "bram-tillotson",   16, 28.00),
    ("endpapers",     "Launch",    "2025-01-25", "agnes-varden",    210,  0.00),
    ("endpapers",     "Lecture",   "2025-04-12", "juno-verrall",    165, 14.00),
    ("endpapers",     "Panel",     "2025-11-22", "delia-stannard",  145, 10.00),
    ("bookwyrm",      "Book Club", "2025-05-03", "elin-morgan",      38,  3.50),
    ("bookwyrm",      "Reading",   "2025-08-16", "dilys-tremain",    52,  5.50),
    ("harbour-page",  "Reading",   "2025-07-12", "juno-verrall",     44,  5.00),
    ("cotton-quarto", "Launch",    "2025-02-08", "yara-tesfaye",    240,  0.00),
    ("cotton-quarto", "Panel",     "2025-06-28", "hal-morrow",      175, 12.00),
    ("cotton-quarto", "Workshop",  "2025-10-11", "yara-tesfaye",     28, 35.00),
    ("signature",     "Reading",   "2025-03-29", "cerys-lloyd",      63,  6.00),
    ("signature",     "Panel",     "2025-09-20", "owain-preece",     84,  9.50),
    ("severn-leaf",   "Lecture",   "2025-04-05", "perrin-oakes",     49,  8.00),
    ("dog-eared",     "Book Club", "2025-05-24", "rab-fingal",       19,  3.00),
    ("candlemas",   "Lecture",   "2025-02-22", "selina-frayne",   132, 15.00),
    ("candlemas",   "Launch",    "2025-07-26", "delia-stannard",  158,  0.00),
    ("chapter-verse", "Panel",     "2025-03-01", "marek-oyelaran",  120, 11.00),
    ("chapter-verse", "Workshop",  "2025-06-11", "delia-stannard",   26, 26.00),
    ("chapter-verse", "Reading",   "2025-10-25", "priya-nandakumar", 71,  7.00),
    ("broads-bindery","Reading",   "2025-05-31", "priya-nandakumar", 57,  5.00),
    ("ex-libris",     "Launch",    "2025-01-18", "ines-calloway",   320,  0.00),
    ("ex-libris",     "Panel",     "2025-04-30", "noor-haddad",     265, 16.00),
    ("ex-libris",     "Lecture",   "2025-09-03", "marek-oyelaran",  198, 18.00),
    ("ex-libris",     "Book Club", "2025-11-15", "hal-morrow",       46,  5.00),
    ("turn-the-page", "Reading",   "2025-06-04", "noor-haddad",      89,  8.00),
    ("turn-the-page", "Signing",   "2025-10-18", "yara-tesfaye",    102,  0.00),
    ("crescent",      "Lecture",   "2025-03-12", "selina-frayne",    94, 12.00),
    ("crescent",      "Reading",   "2025-08-09", "magnus-thole",     68,  6.00),
    ("west-quay",     "Reading",   "2025-05-21", "dilys-tremain",    41,  5.00),
    ("penwith",       "Reading",   "2025-07-02", "orla-finnerty",    35,  4.50),
    ("penwith",       "Workshop",  "2025-09-14", "orla-finnerty",    14, 24.00),
    ("castle-steps",  "Launch",    "2025-05-26", "cerys-lloyd",     190,  0.00),
    ("castle-steps",  "Panel",     "2025-08-30", "elin-morgan",     115, 10.00),
    ("clock-tower",   "Book Club", "2025-04-08", "rab-fingal",       29,  3.00),
    ("cliff-road",    "Reading",   "2025-06-18", "elin-morgan",      47,  5.00),
    ("taff-margin",   "Panel",     "2025-03-06", "bryn-caradoc",     78,  9.00),
    ("taff-margin",   "Launch",    "2025-11-01", "cerys-lloyd",     124,  0.00),
]

# ---------------------------------------------------------------------------
# Claims for the RDF 1.2 layer.  Every one of these is a statement ABOUT a
# statement, which is exactly what RDF 1.1 has no tidy way to say.
# ---------------------------------------------------------------------------

# Sources that make claims.
SOURCES = [
    ("trail-guide-2024",  "The Bookshop Trail Guide, 2024 edition", "guidebook",  0.90),
    ("trail-guide-2019",  "The Bookshop Trail Guide, 2019 edition", "guidebook",  0.60),
    ("county-survey",     "County Booksellers Survey",              "survey",     0.95),
    ("shop-website",      "Shop's own website",                     "self-reported", 0.75),
    ("national-register", "National Register of Booksellers",       "register",   0.99),
    ("local-paper",       "The Marches Advertiser",                 "newspaper",  0.50),
]

# Disputed founding dates: (shop, claimed_year, source, confidence)
# The first row for each shop is the one asserted in the main data.
DISPUTED_FOUNDING = [
    ("ex-libris",    1919, "national-register", 0.99),
    ("ex-libris",    1921, "local-paper",       0.40),
    ("endpapers",    1949, "national-register", 0.97),
    ("endpapers",    1946, "trail-guide-2019",  0.55),
    ("candlemas",  1931, "national-register", 0.98),
    ("candlemas",  1928, "local-paper",       0.35),
    ("gutter-gilt",  1955, "county-survey",     0.92),
    ("gutter-gilt",  1955, "shop-website",      0.80),
    ("castle-steps", 1962, "trail-guide-2024",  0.85),
    ("castle-steps", 1965, "trail-guide-2019",  0.45),
]

# Attendance figures as reported by different sources: (shop, kind, date, figure, source)
DISPUTED_ATTENDANCE = [
    ("ex-libris",     "Launch", "2025-01-18", 320, "shop-website"),
    ("ex-libris",     "Launch", "2025-01-18", 285, "local-paper"),
    ("cotton-quarto", "Launch", "2025-02-08", 240, "shop-website"),
    ("cotton-quarto", "Launch", "2025-02-08", 240, "county-survey"),
    ("endpapers",     "Launch", "2025-01-25", 210, "shop-website"),
    ("endpapers",     "Launch", "2025-01-25", 175, "local-paper"),
]

# Critic ratings, annotated with who said it and when.
# (book, score_out_of_10, critic_name, iso_date, publication)
RATINGS = [
    ("the-clyde-tapes",       9, "H. Ravenscroft", "2025-02-14", "The Marches Advertiser"),
    ("the-clyde-tapes",       7, "P. Odunsi",      "2025-03-02", "Northern Review"),
    ("the-tenement-key",      8, "H. Ravenscroft", "2025-04-09", "The Marches Advertiser"),
    ("the-book-town",         9, "M. Ferriday",    "2025-01-30", "Northern Review"),
    ("a-margin-of-error",     6, "M. Ferriday",    "2025-05-11", "Northern Review"),
    ("the-long-station",     10, "P. Odunsi",      "2025-06-21", "Northern Review"),
    ("orbital-decay",         8, "P. Odunsi",      "2025-02-03", "Northern Review"),
    ("the-flood-meadow",      9, "S. Achebe",      "2025-07-15", "The Coastal Word"),
    ("high-water",            7, "S. Achebe",      "2025-08-19", "The Coastal Word"),
    ("machine-time",          9, "S. Achebe",      "2025-09-05", "The Coastal Word"),
    ("the-dark-sea",          8, "M. Ferriday",    "2025-03-28", "Northern Review"),
    ("a-second-country",     10, "H. Ravenscroft", "2025-10-02", "The Marches Advertiser"),
    ("the-crossing-season",   9, "H. Ravenscroft", "2025-04-22", "The Marches Advertiser"),
    ("granite-and-rain",      8, "S. Achebe",      "2025-11-07", "The Coastal Word"),
    ("saltmarsh-year",        7, "M. Ferriday",    "2025-06-30", "Northern Review"),
    ("the-tarn",              9, "S. Achebe",      "2025-05-08", "The Coastal Word"),
]

# Stock levels, held as annotations on the `bs:stocks` link.  The same facts
# also appear in 1.1 form as bs:StockRecord nodes, so the course can put the
# two modelling styles side by side.
# (shop, book, copies, shelf_price_gbp)
STOCK = [
    ("inkwell",       "the-book-town",         12,  9.99),
    ("inkwell",       "a-margin-of-error",      8, 10.99),
    ("inkwell",       "the-clyde-tapes",        5,  8.99),
    ("marginalia",    "gwreiddiau",             6, 11.50),
    ("marginalia",    "rootstock",                  9, 12.00),
    ("marginalia",    "cerrig-a-chysgod",       3, 10.00),
    ("colophon",      "the-tenement-key",      21, 14.99),
    ("colophon",      "closes-and-wynds",      18, 15.99),
    ("colophon",      "the-glasshouse",         7, 12.99),
    ("colophon",      "cold-harbour",           4, 18.00),
    ("broken-spine",  "the-clyde-tapes",        6,  7.50),
    ("broken-spine",  "dead-reckoning",         4,  7.50),
    ("quire",         "machine-time",          15, 16.99),
    ("quire",         "the-canal-and-the-mill",11, 15.50),
    ("verso",         "the-crossing-season",   14, 13.99),
    ("verso",         "a-second-country",      10, 14.99),
    ("verso",         "the-dark-sea-ar",        5, 17.50),
    ("gutter-gilt",   "links-and-lies",         9, 11.99),
    ("gutter-gilt",   "west-sands",         7, 12.99),
    ("northern-light","the-selkie-ledger",      8, 13.00),
    ("northern-light","sgeulachdan-mara",       5, 14.00),
    ("northern-light","fell-and-force",        12, 12.50),
    ("sea-margin",    "the-selkie-ledger",      6, 13.00),
    ("sea-margin",    "the-tarn-gd",            3, 15.00),
    ("borderprint",   "north-of-the-tweed",     4, 22.00),
    ("borderprint",   "whalebone-street",       7, 13.50),
    ("dales-folio",   "fell-and-force",        16, 12.50),
    ("dales-folio",   "the-limestone-year",    11, 13.99),
    ("dales-folio",   "the-tarn",               9, 14.50),
    ("errata",        "orbital-decay",          8, 11.99),
    ("errata",        "the-long-station",      13, 15.99),
    ("errata",        "the-third-map",          6, 12.50),
    ("pressmark",     "the-marches",            7, 16.00),
    ("pressmark",     "the-flood-meadow",      10, 14.99),
    ("bookbarrow",    "the-tarn",              14, 14.50),
    ("bookbarrow",    "scree",                 12, 15.50),
    ("endpapers",     "minster-yard",          19,  9.99),
    ("endpapers",     "the-chapter-house",     17, 10.99),
    ("endpapers",     "a-cold-coming",         15, 11.99),
    ("endpapers",     "the-jet-workers",        8, 17.00),
    ("bookwyrm",      "y-mor-tywyll",           9, 13.99),
    ("bookwyrm",      "the-dark-sea",          13, 13.99),
    ("bookwyrm",      "the-leat",              10, 14.50),
    ("harbour-page",  "whalebone-street",      11, 13.50),
    ("harbour-page",  "the-jet-workers",        9, 17.00),
    ("harbour-page",  "herring-and-hemp",       3, 24.00),
    ("cotton-quarto", "the-cotton-line",       22, 18.99),
    ("cotton-quarto", "smokestack",            16, 13.99),
    ("cotton-quarto", "machine-time",          20, 16.99),
    ("cotton-quarto", "dockhead",               6, 21.00),
    ("signature",     "gwreiddiau",            11, 11.50),
    ("signature",     "stones-and-shadow",      8, 12.00),
    ("signature",     "afon-hir",               4, 19.00),
    ("severn-leaf",   "the-limestone-year",    10, 13.99),
    ("severn-leaf",   "hedgerow-alphabet",      5, 20.00),
    ("dog-eared",     "minster-yard",           7,  9.99),
    ("dog-eared",     "the-book-town",          9,  9.99),
    ("candlemas",   "the-quarry-glass",       6, 19.50),
    ("candlemas",   "evensong-for-a-thief",   8, 16.00),
    ("candlemas",   "the-orrery",            12, 13.99),
    ("chapter-verse", "the-long-station",      18, 15.99),
    ("chapter-verse", "orbital-decay",         14, 11.99),
    ("chapter-verse", "the-fen-tiger",         10, 12.99),
    ("broads-bindery","saltmarsh-year",        13, 14.99),
    ("broads-bindery","the-broad-and-the-cut", 11, 13.50),
    ("broads-bindery","drainage",               7, 12.99),
    ("ex-libris",     "river-terminus",        24, 14.99),
    ("ex-libris",     "the-glasshouse",        21, 12.99),
    ("ex-libris",     "the-quiet-service",     19, 13.99),
    ("ex-libris",     "a-second-country",      26, 14.99),
    ("ex-libris",     "cold-harbour",           9, 18.00),
    ("ex-libris",     "cold-harbour-he",        2, 26.00),
    ("turn-the-page", "the-crossing-season",   17, 13.99),
    ("turn-the-page", "the-dark-sea-ar",        6, 17.50),
    ("turn-the-page", "the-long-station-cy",    4, 16.00),
    ("crescent",      "the-orrery",            15, 13.99),
    ("crescent",      "pump-room-winter",      13, 12.99),
    ("crescent",      "the-fen-tiger",          8, 12.99),
    ("west-quay",     "the-marches",            9, 16.00),
    ("west-quay",     "granite-and-rain",      11, 15.50),
    ("penwith",       "the-tin-coast",         10, 13.50),
    ("penwith",       "wrecking",               8, 14.50),
    ("penwith",       "the-leat",               7, 14.50),
    ("castle-steps",  "the-mountain-book",      9, 15.00),
    ("castle-steps",  "llyfr-y-mynydd",         5, 16.00),
    ("castle-steps",  "coal-and-chapel",        7, 17.50),
    ("castle-steps",  "the-book-town-cy",       6, 12.00),
    ("clock-tower",   "the-book-town",         11,  9.99),
    ("clock-tower",   "minster-yard",           6,  9.99),
    ("cliff-road",    "cerrig-a-chysgod",       8, 10.00),
    ("cliff-road",    "y-mor-tywyll",          10, 13.99),
    ("cliff-road",    "the-long-station-cy",    5, 16.00),
    ("taff-margin",   "coal-and-chapel",       12, 17.50),
    ("taff-margin",   "the-tramroad",           9, 15.00),
    ("taff-margin",   "rootstock",                 14, 12.00),
]
