# -*- coding: utf-8 -*-
"""The rest of the toolkit.

FEATURES.md is generated by scanning the query bodies, and the first time it
ran it found thirty-six keywords and functions this course talked about in
prose and never actually demonstrated. These queries close that gap. Each one
belongs in an existing module rather than a new one, and `place` puts it
where it reads best -- query ids are permanent, reading order is not.

    python scripts/features.py        # the coverage report that found these
"""

from querycat import q, D11, D12, DTRIG, DFULL, ALL, EDITOR, HOLOS, FUSEKI, ALL_UPDATE

q(
    qid="q126", module="01-first-queries", place=4.5,
    title="Reading a long answer ten at a time",
    asks="Show shops 11 to 20 of the trail, alphabetically.",
    how="LIMIT caps the number of rows; OFFSET says how many to skip first. "
        "Together they page. The part everyone gets wrong is that neither "
        "means anything without ORDER BY: with no order, the second page may "
        "repeat rows from the first, and no engine is doing anything wrong.",
    diagram="""
    ORDER BY ?name          33 shops, in a defined order
    LIMIT 10                take ten
    OFFSET 10               after skipping ten

      page 1   OFFSET  0    Bookbarrow         ... Errata
      page 2   OFFSET 10    Ex Libris          ... The Bookwyrm  <- this
      page 3   OFFSET 20    The Broads Bindery ... The Sea Margin
      page 4   OFFSET 30    Turn the Page      ... West Quay Books

    Thirty-three shops, so the last page has three rows rather
    than ten. A client that stops when a page comes back short is
    doing the right thing; one that stops when a page comes back
    empty makes one extra request and is also fine.

    without ORDER BY:

      +----------------------------------------------------------+
      |  LIMIT 10 OFFSET 10 is "ten rows from somewhere in the    |
      |  middle of an arbitrary sequence". Run it twice and you   |
      |  may get different rows. Page through a whole table that  |
      |  way and you will miss some and see others twice.         |
      +----------------------------------------------------------+

    Order by something unique, too. Ordering by a column with ties
    leaves the tied rows in an arbitrary order between them, and a
    page boundary landing inside a tie has the same problem in
    miniature -- q41 hit exactly this.

    Paging costs the engine the whole sorted answer every time, so
    page 400 is as expensive as pages 1 to 400 together. For a
    large result set that is the thing to design around, not the
    LIMIT.
    """,
    learn=[
        "LIMIT takes n rows; OFFSET skips n first. Neither is meaningful "
        "without ORDER BY.",
        "Order by something unique, or a page boundary inside a group of tied "
        "rows will drop and repeat.",
        "OFFSET n makes the engine produce and discard n rows. Deep paging is "
        "expensive everywhere.",
    ],
    body="""SELECT ?name
WHERE {
  ?shop a          bs:Bookshop ;
        rdfs:label ?name .
}
ORDER BY ?name
LIMIT 10
OFFSET 10""",
    data=D11,
)

q(
    qid="q127", module="02-filtering", place=10.5,
    title="Taking a string apart",
    asks="Build a short sortable code for each shop from its name.",
    how="The string functions compose, and this uses most of them at once: "
        "STRLEN to measure, UCASE and SUBSTR to cut, STRBEFORE and STRAFTER "
        "to split on a marker, CONTAINS and STRSTARTS to test, CONCAT to put "
        "the pieces back together.",
    diagram="""
    "The Harbour Page"

      STRSTARTS(?n, "The ")        true
      STRAFTER(?n, "The ")         "Harbour Page"      drop the article
      STRBEFORE(?bare, " ")        "Harbour"           first word
      SUBSTR(?first, 1, 3)         "Har"
      UCASE( that )                "HAR"
      STRLEN(?n)                   16
      STRENDS(?n, "Books")         false            -> "-"
      CONCAT("HAR", "-", "16", "-")   "HAR-16-"

    +--------------------+------------------+--------+
    | The Harbour Page   | HAR-16-          |     16 |
    | The Inkwell        | INK-11-          |     11 |
    | Castle Steps Books | CAS-18B          |     18 |
    +--------------------+------------------+--------+

    the whole family, and what each is for:

      STRLEN      length in characters, not bytes
      SUBSTR      by position; 1-based, and takes a LENGTH
      UCASE LCASE case, for comparison rather than display
      STRSTARTS   prefix test           STRENDS   suffix test
      CONTAINS    substring test -- cheaper than REGEX (q10)
      STRBEFORE   everything before the first match; "" if absent
      STRAFTER    everything after it;               "" if absent
      CONCAT      joins, and propagates the language tag only when
                  every argument carries the same one

    STRBEFORE and STRAFTER returning "" rather than erroring when
    the marker is missing is the trap: an empty string is a
    perfectly good value, and it will flow through the rest of the
    expression without complaint.
    """,
    learn=[
        "SUBSTR counts from 1 and takes a length, not an end position. "
        "afn:substr does neither -- see q103.",
        "CONTAINS and STRSTARTS say what REGEX would, cost less, and read "
        "better. Keep REGEX for actual patterns.",
        "STRBEFORE and STRAFTER return the empty string when the marker is "
        "absent. Test with CONTAINS first if that matters.",
    ],
    body="""SELECT ?name ?code ?length
WHERE {
  ?shop a          bs:Bookshop ;
        rdfs:label ?name .
  BIND( STR(?name) AS ?plain )
  BIND( IF( STRSTARTS(?plain, "The "), STRAFTER(?plain, "The "), ?plain )
        AS ?bare )
  BIND( IF( CONTAINS(?bare, " "), STRBEFORE(?bare, " "), ?bare )
        AS ?firstWord )
  BIND( STRLEN(?plain) AS ?length )
  BIND( IF( STRENDS(?plain, "Books"), "B", "-" ) AS ?trade )
  BIND( CONCAT( UCASE(SUBSTR(?firstWord, 1, 3)), "-", STR(?length),
                ?trade ) AS ?code )
}
ORDER BY ?code
LIMIT 10""",
    data=D11,
)

q(
    qid="q128", module="02-filtering", place=13.4,
    title="Asking a value what it is",
    asks="For one shop, report the kind and datatype of everything said about "
         "it.",
    how="Four tests sort every RDF term between them -- isIRI, isBLANK, "
        "isLITERAL and isNUMERIC -- and DATATYPE names the type of a literal. "
        "This is what to run when a FILTER is not matching and you cannot see "
        "why, because the answer is almost always that the value is not the "
        "type you assumed.",
    diagram="""
    for each object of bt:shop-inkwell:

      isIRI(?o)      -> IRI          the town it is in
      isLITERAL(?o)  -> literal      its name, year, size
      isNUMERIC(?o)  -> numeric      a subset of the literals
      isBLANK(?o)    -> blank node   none here; see module 16

      DATATYPE(?o)   the type IRI of a literal.

    everything this dataset says about The Inkwell, sorted:

      +-----------------+------------------+----+
      | IRI             |                  | 11 |
      | literal         | rdf:langString   |  1 |   the name
      | literal         | xsd:anyURI       |  1 |   the website
      | literal         | xsd:boolean      |  2 |   cafe, secondhand
      | literal         | xsd:gYear        |  1 |   founded
      | numeric literal | xsd:decimal      |  3 |   coordinates
      | numeric literal | xsd:integer      |  1 |   floor area
      +-----------------+------------------+----+

    Note what is NOT there: a single xsd:string. Every string in
    this dataset carries either a language tag or a datatype, and
    that is deliberate.

    +----------------------------------------------------------+
    |  A language-tagged literal has datatype rdf:langString,   |
    |  never xsd:string. A FILTER written as                    |
    |      FILTER( DATATYPE(?label) = xsd:string )              |
    |  therefore matches none of the labels in this dataset,    |
    |  and that is q11's lesson from the other direction.       |
    +----------------------------------------------------------+

    langMatches is the right test for a language tag, because it
    understands ranges: langMatches(LANG(?x), "en") also matches
    "en-GB", where LANG(?x) = "en" does not.

    STRDT and STRLANG go the other way -- they build a typed or
    tagged literal from a plain string, which is how you repair
    data that arrived untyped.
    """,
    learn=[
        "isIRI, isBLANK, isLITERAL and isNUMERIC partition every RDF term. "
        "DATATYPE names a literal's type.",
        "A language-tagged literal is rdf:langString, not xsd:string. Most "
        "surprising empty results come from this.",
        "langMatches handles language ranges; equality on LANG() does not. "
        "STRDT and STRLANG build typed and tagged literals.",
    ],
    body="""SELECT ?kind ?datatype (COUNT(*) AS ?n)
WHERE {
  bt:shop-inkwell ?p ?o .
  BIND( IF( isIRI(?o),     "IRI",
        IF( isBLANK(?o),   "blank node",
        IF( isNUMERIC(?o), "numeric literal",
                           "literal" ))) AS ?kind )
  BIND( IF( isLITERAL(?o), DATATYPE(?o), "" ) AS ?datatype )
}
GROUP BY ?kind ?datatype
ORDER BY ?kind ?datatype""",
    data=D11,
    extra_prefixes=("rdf",),
)

q(
    qid="q129", module="02-filtering", place=13.5,
    title="Four ways to lose the decimals",
    asks="Round the shelf price of every book, four different ways, and see "
         "where they differ.",
    how="ROUND, FLOOR, CEIL and ABS are the whole of SPARQL's numeric "
        "toolkit, and the differences between the first three only show up on "
        "particular values -- which is why they are worth putting side by "
        "side once rather than reading about.",
    diagram="""
      value    ROUND   FLOOR   CEIL    ABS
      -----    -----   -----   ----    ---
       8.99       9       8      9     8.99
       9.50      10       9     10     9.50
      12.00      12      12     12    12.00
      -3.50      -3      -4     -3     3.50     <- the interesting row

    ROUND takes half away from zero on some engines and to
    positive infinity on others; SPARQL says "to nearest, ties
    toward positive infinity", so -3.5 rounds to -3. Test it
    rather than assuming, if the sign matters.

    +----------------------------------------------------------+
    |  There is no square root and no power. Module 09 is built |
    |  around that fact, and module 15 shows what afn:sqrt and  |
    |  math:pow cost you in portability.                        |
    +----------------------------------------------------------+

    Note the type. ROUND of an xsd:decimal is an xsd:decimal, so
    the answers come back as 8.0 and 12.0 rather than 8 and 12.
    Use xsd:integer() if you want the whole number.

    RAND() returns a double in [0, 1). It is genuinely random, so
    a query using it cannot be checked by comparing answers --
    which is why this one asks whether the value is in range
    rather than what it is.
    """,
    learn=[
        "ROUND, FLOOR, CEIL and ABS are the numeric functions. There is no "
        "sqrt, no pow and no log in standard SPARQL.",
        "Rounding negative numbers is where engines have historically "
        "differed. The specification says ties go toward positive infinity.",
        "RAND() is a real random double in [0, 1). Anything using it is "
        "unrepeatable, so keep it out of anything you need to verify.",
    ],
    body="""SELECT ?rounded ?floored ?ceiled ?absolute ?randInRange (COUNT(*) AS ?books)
WHERE {
  ?record bs:shelfPrice ?price .
  BIND( ROUND(?price)          AS ?rounded )
  BIND( FLOOR(?price)          AS ?floored )
  BIND( CEIL(?price)           AS ?ceiled )
  BIND( ABS(0 - ?price)        AS ?absolute )
  BIND( IF( RAND() >= 0.0 && RAND() < 1.0, "yes", "impossible" )
        AS ?randInRange )
}
GROUP BY ?rounded ?floored ?ceiled ?absolute ?randInRange
ORDER BY ?absolute
LIMIT 8""",
    data=D11,
)

q(
    qid="q130", module="02-filtering", place=13.6,
    title="Pulling a date apart",
    asks="Break every event date into its parts.",
    how="A xsd:dateTime or xsd:date can be taken apart with YEAR, MONTH, DAY "
        "and, where there is a time, HOURS, MINUTES, SECONDS and TIMEZONE. "
        "They return plain numbers, which is what makes grouping by month "
        "possible at all -- there is no date arithmetic in SPARQL beyond "
        "this.",
    diagram="""
    "2024-06-15"^^xsd:date

      YEAR   -> 2024        MONTH -> 6        DAY -> 15

    and for a dateTime, three more:

      HOURS  MINUTES  SECONDS      TIMEZONE / TZ

    what you can do with them:

      GROUP BY (MONTH(?d))         events per month
      FILTER( YEAR(?d) = 2024 )    a year's worth
      ?d < NOW()                   in the past

    what you cannot do:

      ?d + "P1M"^^xsd:duration     no duration arithmetic
      DATEDIFF(?a, ?b)             no such function

    and one thing that is not portable, measured:

      YEAR( "2025-03-08"^^xsd:date )       editor 2025  fuseki 2025
                                           holos  UNBOUND
      YEAR( "...T00:00:00"^^xsd:dateTime ) all three   2025

    HOLOS implements the date functions for xsd:dateTime only, and
    returns the row with the variable unbound rather than raising --
    the failure mode module 15 keeps warning about. So this query
    promotes the date first:

      STRDT( CONCAT( STR(?date), "T00:00:00" ), xsd:dateTime )

    which is the portable way to widen a date, and incidentally the
    clearest use of STRDT there is.

    Subtracting two xsd:dateTime values gives an xsd:duration on
    engines that support it and an error on those that do not, so
    q13 computes an age from YEAR() alone. That is the portable
    way, and it is off by up to a year -- which the query says.

    +----------------------------------------------------------+
    |  MONTH returns 6, not "June" and not "06". Formatting a   |
    |  date for display is not something SPARQL does; do it in  |
    |  whatever consumes the results.                           |
    +----------------------------------------------------------+
    """,
    learn=[
        "YEAR, MONTH, DAY, HOURS, MINUTES, SECONDS and TIMEZONE take a date "
        "apart into numbers -- reliably, on all three engines, only for "
        "xsd:dateTime. STRDT is how you widen an xsd:date to one.",
        "There is no date arithmetic and no formatting. Grouping and "
        "comparison are what the parts are for.",
        "NOW() is fixed for the whole query, so two calls in one query always "
        "agree -- which is what makes it usable at all.",
    ],
    body="""SELECT ?year ?month (COUNT(*) AS ?events)
WHERE {
  ?event a           bs:Event ;
         bs:eventDate ?date .
  # xsd:date, promoted to xsd:dateTime so that every engine can read
  # it -- see the diagram. STRDT builds a typed literal from a string.
  BIND( STRDT( CONCAT( STR(?date), "T00:00:00" ), xsd:dateTime ) AS ?at )
  BIND( YEAR(?at)  AS ?year )
  BIND( MONTH(?at) AS ?month )
  BIND( DAY(?at)   AS ?day )
}
GROUP BY ?year ?month
ORDER BY ?year ?month""",
    data=D11,
)

q(
    qid="q131", module="03-optional-and-negation", place=98.5,
    title="IN, NOT IN, and when to use VALUES instead",
    asks="Find the shops in three named towns, then everything outside them.",
    how="IN tests whether a value is one of a list, and NOT IN is its "
        "negation. Both are expressions, so they live in a FILTER and can "
        "only narrow what a pattern already found. VALUES is a pattern, so it "
        "can supply rows rather than filter them -- which is the difference "
        "that decides which to reach for.",
    diagram="""
    FILTER( ?town IN (bt:place-hay-on-wye,
                      bt:place-wigtown,
                      bt:place-sedbergh) )

      an EXPRESSION. The pattern has already found every shop;
      this throws most of them away.

    VALUES ?town { bt:place-hay-on-wye
                   bt:place-wigtown
                   bt:place-sedbergh }

      a PATTERN. Three rows exist before the join runs, and the
      engine can start from them.

    +--------------+---------------------------+------------------+
    |              | reads as                  | engine can       |
    +--------------+---------------------------+------------------+
    | IN           | filter, after the match   | rarely optimise  |
    | VALUES       | data, before the match    | drive the join   |
    | NOT IN       | filter, after the match   | no equivalent    |
    +--------------+---------------------------+------------------+

    NOT IN has no VALUES form, because a negative has no rows to
    supply. MINUS and NOT EXISTS are the pattern-shaped negations
    (q17), and IN is a list of values rather than a graph pattern.

    Two more things worth knowing. IN evaluates its list left to
    right and stops at the first match, so put the likely ones
    first if the list is long. And an error in the list -- an
    unbound variable, say -- makes the whole expression an error
    rather than false, which is q19's territory.
    """,
    learn=[
        "IN and NOT IN are expressions and belong in a FILTER. They narrow; "
        "they cannot supply rows.",
        "VALUES does the positive case better, because the engine can start "
        "from the list rather than filter down to it. Compare q98.",
        "NOT IN has no VALUES equivalent. For a negative, that is what MINUS "
        "and NOT EXISTS are for.",
    ],
    body="""SELECT ?where (COUNT(*) AS ?shops)
WHERE {
  ?shop a            bs:Bookshop ;
        bs:locatedIn ?town .
  BIND( IF( ?town IN ( bt:place-hay-on-wye,
                       bt:place-wigtown,
                       bt:place-sedbergh ),
            "a book town", "somewhere else" ) AS ?where )
  FILTER( ?town NOT IN ( bt:place-york ) )
}
GROUP BY ?where
ORDER BY ?where""",
    data=D11,
)

q(
    qid="q132", module="04-aggregation", place=26.5,
    title="DISTINCT, REDUCED, and what each costs",
    asks="List the towns that have a bookshop, without repeating any.",
    how="DISTINCT removes every duplicate, which means the engine has to hold "
        "or sort the whole answer to know what it has already seen. REDUCED "
        "permits it to remove some and is not obliged to remove any, which "
        "lets it drop the adjacent ones as they stream past and keep nothing "
        "in memory.",
    diagram="""
    33 shops -> 26 towns, with duplicates in between

      DISTINCT   every duplicate gone.       Guaranteed.
      REDUCED    duplicates MAY be gone.     Permitted, not required.

    +-------------+-------------------+-------------------------+
    |             | result            | cost                    |
    +-------------+-------------------+-------------------------+
    | (neither)   | 33 rows           | none                    |
    | DISTINCT    | 26 rows           | remembers what it saw   |
    | REDUCED     | 26 to 33 rows     | may remember nothing    |
    +-------------+-------------------+-------------------------+

    and this exact query, measured:

      editor  26 rows     duplicates dropped
      holos   26 rows     duplicates dropped
      fuseki  33 rows     duplicates kept

    All three are correct. REDUCED permits removal and requires
    nothing, so an engine that does the cheap thing and an engine
    that does the thorough thing both conform -- and here Jena is
    the one that declines to pay. There is no bug to report.

    That is what makes REDUCED awkward to teach and awkward to
    use: the one guarantee it gives you is that it gives you no
    guarantee.

    So REDUCED is not "DISTINCT but faster". It is "I do not mind
    duplicates, and I would rather you did not pay to remove
    them". Use it when the consumer deduplicates anyway, and use
    DISTINCT whenever the count matters.

    +----------------------------------------------------------+
    |  COUNT(DISTINCT ?x) is a different thing again, and it    |
    |  does what it says -- q25 uses it. There is no            |
    |  COUNT(REDUCED ?x).                                       |
    +----------------------------------------------------------+
    """,
    learn=[
        "DISTINCT guarantees no duplicates and costs memory or a sort. "
        "REDUCED permits duplicate removal without requiring it.",
        "A REDUCED result is not reproducible across engines by definition. "
        "Never depend on its row count.",
        "COUNT(DISTINCT ?x) is unrelated to the solution modifier and is what "
        "you want when counting distinct values.",
    ],
    body="""SELECT REDUCED ?town
WHERE {
  ?shop a            bs:Bookshop ;
        bs:locatedIn ?place .
  ?place rdfs:label  ?town .
  FILTER( LANG(?town) = "en" )
}
ORDER BY ?town""",
    data=D11,
    notes="engines-differ: and by design. Jena returns all 33 rows; Comunica "
          "and HOLOS return the 26 distinct ones. REDUCED permits duplicate "
          "removal without requiring it, so every one of those answers "
          "conforms.",
)

q(
    qid="q133", module="05-property-paths", place=30.5,
    title="A hop that may not be there",
    asks="List every place with its council area, falling back to the place "
         "itself where there is no council above it.",
    how="The ? modifier means zero or one hop. It is the path form of "
        "OPTIONAL and it behaves quite differently: where OPTIONAL leaves a "
        "variable unbound, a zero-length path binds the variable to the "
        "starting node. That is useful exactly as often as it is surprising.",
    diagram="""
    ?place bs:within? ?up

    Both cases apply to every place, so each one produces TWO rows:

      Hay-on-Wye   zero hops  ->  ?up = Hay-on-Wye
      Hay-on-Wye   one hop    ->  ?up = Powys

      +--------------------+--------------------+
      | Aberystwyth        | Aberystwyth        |
      | Aberystwyth        | Ceredigion         |
      | Bath               | Bath               |
      | Bath               | Somerset           |
      +--------------------+--------------------+

    That doubling is the thing to expect. A ? path does not choose
    between zero and one hop; it matches both, and the row count
    doubles for every node that has a parent.

    +----------------------------------------------------------+
    |  bs:within?     always binds. Zero hops binds ?up to      |
    |                 ?place itself -- never unbound.           |
    |                                                           |
    |  OPTIONAL {     binds or leaves unbound. BOUND(?up)       |
    |    ?place         tells them apart; with the path there   |
    |    bs:within ?up  is nothing to tell apart.               |
    |  }                                                        |
    +----------------------------------------------------------+

    So ? is the wrong tool when you need to know whether the hop
    happened, and the right one when you want "this or its parent"
    treated uniformly -- a lookup that should work whether it is
    given a town or the county containing it, say.

    The four path modifiers, side by side:

      p       exactly one hop
      p?      zero or one          always binds
      p+      one or more
      p*      zero or more         always binds

    The two that include zero are the two that always produce a
    row, which is why q29 warns that ?x bs:within* ?y matches
    every node against itself.
    """,
    learn=[
        "p? matches zero or one hop, and the zero case binds the variable to "
        "the starting node rather than leaving it unbound.",
        "Use OPTIONAL, not p?, when you need to know whether the hop "
        "happened. BOUND() has nothing to test after a ? path.",
        "p? and p* both include the zero-length case, so both always produce "
        "at least the node itself.",
    ],
    body="""SELECT ?place ?up (COUNT(*) AS ?rows)
WHERE {
  ?p     a           bs:Settlement ;
         rdfs:label  ?place .
  ?p     bs:within?  ?u .
  ?u     rdfs:label  ?up .
  FILTER( LANG(?place) = "en" && LANG(?up) = "en" )
}
GROUP BY ?place ?up
ORDER BY ?place ?up
LIMIT 8""",
    data=D11,
)

q(
    qid="q134", module="11-sparql-1-2", place=63.5,
    title="Naming a statement in the query itself",
    asks="Find the shop whose founding year somebody disputes, using the "
         "reifier syntax rather than a variable.",
    how="<< s p o ~ ?r >> is the reifier form: it matches the triple and "
        "binds ?r to the reifier that identifies it, in one piece of syntax. "
        "It is the query-side counterpart of the annotation syntax the data "
        "is written in, and it saves the two-step of matching the triple term "
        "and then finding what rdf:reifies it.",
    diagram="""
    the data, written with annotation syntax:

      bt:shop-ex-libris bs:founded "1919"^^xsd:gYear
          {| bs:statedOn bt:source-guide ; bs:confidence 0.7 |} .

    what that means underneath:

      _:r rdf:reifies <<( bt:shop-ex-libris bs:founded "1919" )>> .
      _:r bs:statedOn bt:source-guide .

    two ways to get at it:

      the long way                    the reifier syntax
      ------------                    ------------------
      ?r rdf:reifies ?t .             << ?s bs:founded ?y ~ ?r >>
      BIND(SUBJECT(?t) AS ?s)         ?r bs:confidence ?c .
      BIND(OBJECT(?t)  AS ?y)
      ?r bs:confidence ?c .

    Same answer, and the second says what it means. The ~ ?r part
    is optional: << ?s ?p ?o >> on its own matches the triple
    through some reifier without naming it.

    +----------------------------------------------------------+
    |  A reifier identifies a STATEMENT, not a fact. Two        |
    |  reifiers on the same triple are two separate claims      |
    |  about it -- one from a guidebook, one from the shop --   |
    |  and that is the whole point of the mechanism.            |
    +----------------------------------------------------------+
    """,
    learn=[
        "<< s p o ~ ?r >> matches a triple and binds its reifier in one step.",
        "The reifier is what carries the annotations. The triple term is the "
        "statement; the reifier is this particular assertion of it.",
        "Reifiers are usually blank nodes, so do not sort or page on one -- "
        "module 16 is about why.",
    ],
    body="""SELECT ?shop ?year ?confidence
WHERE {
  << ?shop bs:founded ?year ~ ?r >> .
  ?r bs:confidence ?confidence .
}
ORDER BY ?confidence ?shop""",
    data=D12,
    extra_prefixes=("rdf",),
)

q(
    qid="q135", module="15-beyond-the-standard", place=101.5,
    title="The XPath maths library",
    asks="Compute a distance with math:sqrt and a growth figure with "
         "math:pow.",
    how="math: is the XPath 3.1 maths library, and Jena registers it. It "
        "covers what afn: covers and rather more -- pow, log, exp, the "
        "trigonometric functions -- and unlike afn: it is at least a "
        "published specification, even if not one SPARQL requires.",
    diagram="""
      math:sqrt(x)        math:pow(x, y)      math:exp(x)
      math:log(x)         math:log10(x)       math:sin  cos  tan
      math:atan2(y, x)    math:pi()

    measured on the three engines:

      math:sqrt   editor  error   holos  error   fuseki  yes
      math:pow    editor  error   holos  error   fuseki  yes

    So this is the narrowest of the extension libraries in this
    course: one engine of the three. afn:sqrt (q101) covers the
    same ground on two of them, which makes afn: the better bet
    if you are going to depend on an extension at all.

    +----------------------------------------------------------+
    |  What to take from module 15 as a whole: there are four   |
    |  function libraries here and no two engines agree on      |
    |  which they have. Write the standard version (q104),      |
    |  measure whether it is fast enough, and only then reach   |
    |  for a library -- with a comment saying which engine you  |
    |  have just tied yourself to.                              |
    +----------------------------------------------------------+
    """,
    learn=[
        "math: is the XPath maths library: sqrt, pow, log, exp and the "
        "trigonometric functions. Jena has it; the other two do not.",
        "It overlaps afn: without replacing it, and afn: is available on more "
        "of these engines.",
        "Four libraries, three engines, no agreement. That is the state of "
        "extension functions, and it is why the portable rewrite matters.",
    ],
    body="""SELECT ?name ?km ?doubled
WHERE {
  bt:place-york bs:easting ?ye ; bs:northing ?yn .
  ?shop a           bs:Bookshop ;
        rdfs:label  ?name ;
        bs:easting  ?se ;
        bs:northing ?sn .
  BIND( (?se - ?ye) * (?se - ?ye) + (?sn - ?yn) * (?sn - ?yn) AS ?d2 )
  BIND( ROUND( math:sqrt(?d2) / 100 ) / 10 AS ?km )
  BIND( ROUND( math:pow(?km, 2) )          AS ?doubled )
}
ORDER BY ?km
LIMIT 8""",
    data=DFULL,
    engines=(FUSEKI,),
    notes="Fuseki only. Comunica and HOLOS both raise on math:, so the "
          "portable version of this is q104 and the two-engine version is "
          "q101.",
)

q(
    qid="q136", module="16-blank-nodes", place=114.5,
    title="Names you can compute",
    asks="Mint identifiers three ways -- a hash, a URI-safe string, and a "
         "fresh blank node -- and see which are stable.",
    how="q114 skolemised by hand. These are the functions for doing it "
        "properly: MD5 and the SHA family hash a string to a fixed-length "
        "digest, ENCODE_FOR_URI makes an arbitrary string safe to put in an "
        "IRI, and BNODE() mints a fresh blank node. Only the first two are "
        "repeatable, and that is the entire lesson.",
    diagram="""
    "The Harbour Page"

      MD5(?s)              d41d8cd9...  32 hex characters
      SHA256(?s)           e3b0c442...  64
      ENCODE_FOR_URI(?s)   The%20Harbour%20Page
      BNODE()              _:b0, _:b1, ...   a new one each solution
      STRUUID()            36 characters, random
      UUID()               a urn:uuid: IRI, 45 characters

    +---------------------+------------+---------------------------+
    |                     | repeatable | good for                  |
    +---------------------+------------+---------------------------+
    | MD5 / SHA256        | yes        | an id derived from content|
    | ENCODE_FOR_URI      | yes        | a readable id from a label|
    | BNODE()             | NO         | structure in a template   |
    | UUID / STRUUID      | NO         | a genuinely new thing     |
    +---------------------+------------+---------------------------+

    Repeatable is what makes a migration re-runnable (q121). Run
    the same INSERT twice with a hashed IRI and the second run
    changes nothing; run it with UUID() and you get a second copy
    of everything.

    This query asks for the LENGTH of the random values rather
    than the values, because a random value cannot be compared
    across three engines -- which is itself the point being made.

    MD5 is fine here and is not fine for anything security-shaped.
    SHA256 costs nothing extra; prefer it by habit.
    """,
    learn=[
        "MD5, SHA1, SHA256, SHA384 and SHA512 hash a string. The digest is "
        "stable, so an IRI built from one is repeatable.",
        "ENCODE_FOR_URI makes a string safe for an IRI path. It is the "
        "readable alternative to a hash.",
        "BNODE(), UUID() and STRUUID() produce something new every time. "
        "Never use them where a re-run must produce the same graph.",
    ],
    body="""SELECT ?name ?digest ?safe ?uuidLength ?struuidLength
WHERE {
  ?shop a          bs:Bookshop ;
        rdfs:label ?name .
  BIND( SUBSTR( SHA256( STR(?name) ), 1, 12 ) AS ?digest )
  BIND( ENCODE_FOR_URI( STR(?name) )          AS ?safe )
  BIND( STRLEN( STR( UUID() ) )               AS ?uuidLength )
  BIND( STRLEN( STRUUID() )                   AS ?struuidLength )
  BIND( BNODE()                               AS ?fresh )
  FILTER( isBLANK(?fresh) )
}
ORDER BY ?name
LIMIT 6""",
    data=D11,
)

q(
    qid="q137", module="17-updating-the-data", place=122.5,
    title="Emptying, moving and merging graphs",
    asks="Empty one graph, move a second into a third, and merge a fourth "
         "into it.",
    how="q122 covered COPY and DROP. These are the other three, and the "
        "distinctions between them are the whole of the vocabulary: CLEAR "
        "empties but keeps the name, MOVE is a copy that removes the source, "
        "and ADD merges without emptying the destination first.",
    diagram="""
    CLEAR GRAPH <a>     a is empty. The name still exists.
    DROP  GRAPH <a>     a is gone. Asking for it is an error.

    MOVE <a> TO <b>     b emptied, a's contents moved in, a dropped
    COPY <a> TO <b>     b emptied, a's contents copied in, a kept
    ADD  <a> TO <b>     b KEPT, a's contents added, a kept

    applied to the trail dataset:

      CLEAR GRAPH bt:graph-claims       243 triples -> 0, name kept
      MOVE bt:graph-trail TO bt:graph-archive
                                        trail gone, archive has 429
      ADD bt:graph-people TO bt:graph-books
                                        books 918 + people 301 = 1219

    +----------------------------------------------------------+
    |  ADD is the one to reach for when merging, and the one    |
    |  people reach for COPY instead of. COPY silently empties  |
    |  the destination first, so a merge written with COPY      |
    |  destroys whatever was already there.                     |
    +----------------------------------------------------------+

    LOAD <url> INTO GRAPH <g> is the sixth of these, and it
    fetches over the network. That makes it the same exposure as
    SERVICE (q108): a URL the requester chose, fetched by your
    server, from inside your network. HOLOS refuses remote LOAD
    for that reason, and an endpoint that allows it should have an
    allow-list in front of it.

    All six are also SILENT-able: CLEAR SILENT GRAPH <a> succeeds
    rather than failing when there is no such graph.
    """,
    learn=[
        "CLEAR empties a graph and keeps its name; DROP removes both.",
        "MOVE, COPY and ADD differ in two ways: whether the destination is "
        "emptied first, and whether the source survives. ADD is the merge.",
        "LOAD fetches a URL of the requester's choosing, which is why a "
        "careful engine refuses it or puts an allow-list in front.",
    ],
    body="""CLEAR GRAPH bt:graph-claims ;

MOVE bt:graph-trail TO bt:graph-archive ;

ADD bt:graph-people TO bt:graph-books""",
    verify="""SELECT ?graph (COUNT(*) AS ?triples)
WHERE {
  GRAPH ?graph { ?s ?p ?o }
}
GROUP BY ?graph
ORDER BY ?graph""",
    data=DTRIG,
    engines=(HOLOS, FUSEKI),
    notes="Fuseki and HOLOS, for the same reason as q122. Note that "
          "bt:graph-claims survives as a name with nothing in it, so it "
          "disappears from a result grouped by GRAPH -- an empty graph has no "
          "triples to group.",
)


q(
    qid="q138", module="11-sparql-1-2", place=67.5,
    title="Building and matching language tags",
    asks="Which labels carry a language tag, which of them are English, and "
         "how do you add a tag to a string that has none?",
    how="Four functions round out the language handling. hasLANG asks whether "
        "a literal is tagged at all; langMatches compares a tag against a "
        "range, which is what makes en-GB an English label; STRLANG builds a "
        "tagged literal from a plain string, and STRLANGDIR builds one that "
        "also carries a direction.",
    diagram="""
    hasLANG("Hay-on-Wye"@en)        true
    hasLANG("Hay-on-Wye")           false
    hasLANG(220)                    false

    langMatches( LANG(?x), "en" )   the RIGHT test
      "en"     matches              "en-GB"  matches
      "en-US"  matches              "cy"     does not

    LANG(?x) = "en"                 the test people write
      "en"     matches              "en-GB"  DOES NOT

    +----------------------------------------------------------+
    |  A language range is a prefix match on subtags, not a     |
    |  string comparison. Data that arrives with regional tags  |
    |  disappears from every query written the second way, and  |
    |  it disappears silently.                                  |
    +----------------------------------------------------------+

    going the other way, building a literal:

      STRLANG("Hay-on-Wye", "en")            "Hay-on-Wye"@en
      STRLANGDIR("البحر المظلم", "ar", "rtl")   ...@ar--rtl

    STRLANG is how untagged text gets repaired on the way in.
    STRLANGDIR is its RDF 1.2 counterpart, and the direction is
    what tells a renderer which way to lay the text out -- q67 is
    where that matters.

    "*" as a range matches anything tagged at all, which makes
    langMatches(LANG(?x), "*") a wordier hasLANG(?x).

    measured on this dataset:

      tagged, English     410 labels
      tagged, other        34 labels
      no tag                0

    The repair branch never fires, because every label here was
    written with a tag. That is what a clean dataset looks like,
    and it is worth knowing that yours is unusual if it matches.
    """,
    learn=[
        "langMatches compares a language tag against a range, so \"en\" "
        "matches \"en-GB\". Equality on LANG() does not, and loses data "
        "silently.",
        "hasLANG tests whether a literal is tagged at all -- the SPARQL 1.2 "
        "way of writing LANG(?x) != \"\".",
        "STRLANG and STRLANGDIR build tagged literals from plain strings, "
        "which is how untagged text gets repaired.",
    ],
    body="""SELECT ?tagged ?english (COUNT(*) AS ?labels)
WHERE {
  ?thing rdfs:label ?label .
  BIND( IF( hasLANG(?label), "tagged", "no tag" ) AS ?tagged )
  BIND( IF( hasLANG(?label) && langMatches( LANG(?label), "en" ),
            "English", "other" ) AS ?english )

  # The repair, on anything that arrived without a tag.
  BIND( IF( hasLANG(?label), ?label,
            STRLANG( STR(?label), "en" ) ) AS ?repaired )
  BIND( STRLANGDIR( STR(?label), "ar", "rtl" ) AS ?asArabic )
}
GROUP BY ?tagged ?english
ORDER BY ?tagged ?english""",
    data=D12,
)

q(
    qid="q139", module="17-updating-the-data", place=122.7,
    title="Loading a file from the web",
    asks="Fetch a graph over HTTP and put it in a named graph.",
    how="LOAD takes a URL, fetches whatever RDF is there, and adds it. It is "
        "the fastest way to get a file into a store and the operation most "
        "worth being careful about, because the URL comes from whoever wrote "
        "the request rather than from whoever runs the server.",
    diagram="""
    LOAD <https://raw.githubusercontent.com/.../04-bookshops.ttl>
      INTO GRAPH bt:graph-imported

    588 triples arrive in a graph that did not exist before.

      LOAD <url>                    into the default graph
      LOAD <url> INTO GRAPH <g>     into a named one
      LOAD SILENT <url>             carry on if the fetch fails

    +----------------------------------------------------------+
    |  Same exposure as SERVICE (q108). The server makes an     |
    |  HTTP request to an address a stranger named, from        |
    |  inside your network:                                     |
    |                                                           |
    |      LOAD <http://169.254.169.254/latest/meta-data/>      |
    |                                                           |
    |  HOLOS refuses remote LOAD outright, for that reason.     |
    |  Fuseki allows it, so an open update endpoint is an       |
    |  open fetcher as well as an open writer.                  |
    +----------------------------------------------------------+

    The Graph Store Protocol does the same job over plain HTTP
    and puts the choice of file on the client rather than in the
    query -- see "Talking to an endpoint". For loading your own
    data that is the better tool; LOAD is for when the request
    itself has to say where the data comes from.

    Formats: the fetched document is parsed by its content type,
    so a server that serves Turtle as text/plain will produce a
    parse error rather than a graph. That is the commonest reason
    a LOAD of a working URL fails.
    """,
    learn=[
        "LOAD fetches a URL and adds the triples, optionally INTO GRAPH. "
        "SILENT stops a failed fetch from failing the request.",
        "The URL is chosen by the request, not the operator. Treat an update "
        "endpoint as a way to make your server fetch arbitrary addresses.",
        "The Graph Store Protocol is the better route for loading your own "
        "files, because the client supplies the bytes.",
    ],
    body="""LOAD <https://raw.githubusercontent.com/pwin/SPARQL_Course/main/data/04-bookshops.ttl>
  INTO GRAPH bt:graph-imported""",
    verify="""SELECT ?graph (COUNT(*) AS ?triples)
WHERE {
  GRAPH ?graph { ?s ?p ?o }
}
GROUP BY ?graph
ORDER BY ?graph""",
    data=DTRIG,
    engines=(FUSEKI,),
    network=True,
    notes="Fuseki only, and it needs the internet. HOLOS refuses remote LOAD "
          "for the reason in the diagram; the browser editor cannot run an "
          "update at all.",
)
